language: node_js
node_js: stable
cache:
  bundler: true
  directories:
    - node_modules
    - public

install:
  - npm install
script:
  - npm run test:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  local_dir: public
#  target_branch: gh-pages
#  repo: $GH_REF
  on:
    branch: master

env:
 global:
   - GH_REF: be-fe/picidae-theme-eux-blog