language: node_js
node_js: stable
cache:
  bundler: true
  directories:
    - node_modules
    - public

install:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_MESSAGE
  - npm install

jobs:
  include:
    - stage: Robot
      allow_failure: true
      script: curl 'http://qy.im.baidu.com/msgt/api/sendMsgToGroup?access_token=de00428530d2ec16534c83f9818787f3' -d '{"to":1605096,"access_token":"de00428530d2ec16534c83f9818787f3","msg_type":"text","content":"啦啦啦"}'


    - stage: Github Pages
#      allow_failure: true
      script: npm run build
      deploy:
        edge:
          branch: v1.8.47
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: public
        target-branch: master
        repo: $GH_REF
      env: GH_REF=be-fe/be-fe.github.io